axis_linear: 1
scale_linear: 0.7
scale_linear_turbo: 1.5
step_linear: 0.07  # maximum difference between consecutive commands.


axis_angular: 3
scale_angular: 0.4
step_angular: 0.04  # maximum difference between consecutive commands.

enable_button: 8  # L2 shoulder button
enable_turbo_button: 10  # L1 shoulder button

