# Teleop configuration for PS4 joystick using the x-pad configuration.
teleop_twist_joy:
  axis_linear: 4
  scale_linear: 0.7
  scale_linear_turbo: 1.4
  axis_angular: 3
  scale_angular: 1.4
  enable_button: 4
  enable_turbo_button: 5
  step_linear: 0.01
  step_angular: 0.035

joy_node:
  deadzone: 0.1
  autorepeat_rate: 20
